services:
  backend:
    build:
      context: .
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "4173:4173"
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
